sudo: required
language: generic

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 #make sure gcloud skip any action for mannual input
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-322608 #same line run in gcloud shell
  - gcloud config set compute/zone asia-east1-a #same line run in gcloud shell
  - gcloud container clusters get-credentials multi-cluster #same line run in gcloud shell
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker build -t yajilin/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true yaji/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
